#!/bin/bash

DOCKER_COMPOSE_PATH="/media/DATA/Projekte/Docker/projects/"
COMPLETE_DOCKER_COMPOSE_PATH=$DOCKER_COMPOSE_PATH
LOG_PATH="/home/$USER/log/"
LOG_FILE_NAME="server"

function initLog() {
    now=$(date +%Y%m%d%H%M%S)
    LOG_FILE_NAME=$LOG_FILE_NAME.$now
    echo $LOG_FILE_NAME
}

function writeLog() {
    echo $1 >> $LOG_PATH$LOG_FILE_NAME
}

function printUsage() {
    echo "Usage: \n"
    echo $0 
}

function startServer() {
    initLog
    cd "$DOCKER_COMPOSE_PATH$PROJECT/$ENVIRONMENT" && exec docker-compose up
}

function stopServer() {
    initLog
    cd "$DOCKER_COMPOSE_PATH$PROJECT/$ENVIRONMENT" && exec docker-compose kill
}

function destroyServer() {
    initLog
    cd "$DOCKER_COMPOSE_PATH$PROJECT/$ENVIRONMENT" && exec docker-compose down
}

if [ $# -lt 2 ]; then
    printUsage
    exit 1
fi

ACTION=$1
PROJECT=$2
ENVIRONMENT=$3

if [ -z $3 ]; then
    ENVIRONMENT="prod"
fi

case "$ACTION" in 
    "start")
        startServer
        ;;
    "stop")
        stopServer
        ;;
    "destroy")
        destroyServer
        ;;
    "-h"|"--help")
        printUsage
        ;;
    *)
        echo "Unknown Action $ACTION"
        printUsage
        break;
esac

echo $ACTION $PROJECT $ENVIRONMENT
